### ISSUE TITLE
.txt

### ISSUE THREAD

**Issue by ghunter717** [astro-pi/python-sense-hat#107]
closed

**Comment by rzr** [comment]
Please edit or close this ticket , btw is this project still maintained if not it could be xfered to @abandonware org

https://rzr.github.io/rzr-presentations/docs/abandonware

**Comment by bsimmo** [comment]
> Please edit or close this ticket , btw is this project still maintained if not it could be xfered to @abandonware org
> 
> https://rzr.github.io/rzr-presentations/docs/abandonware

It can't change much as it is used by the ESA, RPF etc for various AstroPi competitions.
I believe updating the two Pi's with SenseHATs on the ISS isn't so easy and school and groups use a duplicate of that setup.

**Comment by rzr** [comment]
ok thx for feedback, I have opened a couple of PR though:
https://github.com/astro-pi/python-sense-hat/pulls/rzr
