### ISSUE TITLE
rpi4b ubuntu16.04 error

### ISSUE THREAD

**Issue by maziyao** [astro-pi/python-sense-hat#114]
ubuntu@ubiquityrobot:~/python-sense-hat-master$ sudo apt-get install sense_hat
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package sense_hat

**Comment by G3zz** [comment]
Hello, Ubuntu 16.04 reached EOL on April 30, 2021. You should be able to install the library on a more recent version of Ubuntu.
