### ISSUE TITLE
sense-hat V 1.0 with latest driver

### ISSUE THREAD

**Issue by hb9cvh** [astro-pi/python-sense-hat#125]
My sense-hat is now on a new Rpi 3+ with PiOS Bullseye and latest python-sense-hat.
This little program :

> from sense_hat import SenseHat
> sense = SenseHat()
> sense.show_message("Hello World")

Display the message but show: 

> WARNING:root:Failed to initialise TCS34725 colour sensor. (sensor not present)

What can I do?

**Comment by bsimmo** [comment]
You ignore it.

I wish they didn't display this message as it brings a lot of worry and
comments like yours to users.

Basically they made a new version of the sensehat a year or so ago for the
ISS/AstroPi missions that has a light sensor on it, the retail (original
version) does not have it. And that is what it is saying.

They need to write in a SenseHAT version check so if it is not the v2
(which we cannot buy but is on the ISS) then do not display to user.

**Comment by bsimmo** [comment]
They should change (hopefully to stop users being worried about something
they don't even haven)
logging.warning(e)
to whatever it is that doesn't normally show this error in 'logging' , then
users can override the message logging level IF they are having problems
with it and it comes to debugging the hardware.

Also Add logging/debug information in the documents.

Or have it check the SenseHAT version first and then only check for it?

:-)

But you've made me crack out my sensehats again and have a play :-)

**Comment by G3zz** [comment]
Thanks for your feedback - the latest version (2.5.1) has downgraded that output to debug level, so as to not cause confusion. The documentation is in the process of being updated too
