### ISSUE TITLE
Clear Screen (Clear Pixels)

### ISSUE THREAD

**Issue by zacharyeast** [astro-pi/python-sense-hat#99]
https://github.com/zacharyeast/Sense-Hat/blob/master/Clear%20LED's

Here is a simple but long way to clear all the pixels. Let me know if you know a shorter way!

**Comment by bsimmo** [comment]
sense.clear()

or
sense.clear(R, G, B)
and pick your colour.

as per the documentation.

**Comment by zacharyeast** [comment]
Hello, 

Thanks! For some reason it seemed like sense.clear() didn't clear it every time for me.  That does work perfectly now though, so not sure what happened.
